# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'WallhavenBrowser' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WallhavenBrowser
  pod 'Kingfisher', '~> 3.0'
  pod 'Kanna', '~> 2.0.0'
  pod 'Toast-Swift', '~> 2.0.0'
end
